version: 2

shared: &shared
    working_directory: ~/build_directory/algoliasearch-magento-2
    steps:
        - checkout

        - run:
            name: Override the Algolia extension with the cloned one
            command: |
                cd ~/magento_directory/vendor/algolia
                rm -rf algoliasearch-magento-2
                cp -R ~/build_directory/algoliasearch-magento-2 ~/magento_directory/vendor/algolia
                cd ~/magento_directory
                composer dump-autoload

        - run:
            name: Start database server
            command: |
                sudo service mysql start
                sleep 2
                ps aux | grep mysql

        - run:
            name: Install the extension
            command: |
                cd ~/magento_directory
                php -dmemory_limit=-1 bin/magento module:enable Algolia_AlgoliaSearch
                php -dmemory_limit=-1 bin/magento setup:upgrade

        - run:
            name: Get the right tests config for DB and administration
            command: |
                mv ~/build_directory/algoliasearch-magento-2/dev/tests/install-config-mysql.php ~/magento_directory/dev/tests/integration/etc/install-config-mysql.php

        - run:
              name: Before setup
              command: |
                  wget https://alg.li/algolia-keys && chmod +x algolia-keys

        - run:
            name: Run tests
            command: |
                cd ~/magento_directory/dev/tests/integration
                export CI_BUILD_NUM=$CIRCLE_BUILD_NUM
                export CI_PROJ_USERNAME=$CIRCLE_PROJECT_USERNAME
                export CI_PROJ_REPONAME=$CIRCLE_PROJECT_REPONAME
                eval $(~/build_directory/algoliasearch-magento-2/algolia-keys export)
                php -dmemory_limit=-1 ../../../vendor/bin/phpunit ../../../vendor/algolia/algoliasearch-magento-2/Test

jobs:
    "magento-2.2":
        <<: *shared
        docker:
            - image: algolia/magento2-circleci:v2-2.2.8

    "magento-2.3":
        <<: *shared
        docker:
            - image: algolia/magento2-circleci:v2-2.3.0

    "quality-tools":
        docker:
            - image: algolia/magento2-circleci:v2-2.3.0
        working_directory: ~/build_directory/algoliasearch-magento-2
        steps:
            - checkout
            - run:
                name: Setting permissions
                command: |
                    sudo chown circleci:circleci ~/.composer/
            - restore_cache:
                  keys:
                      - composer-v3-{{ checksum "composer.json" }}
                      - composer-v3-
                      
            - run:
                  name: Prepare environment
                  command: |
                      sudo composer self-update
                      composer config http-basic.'repo.magento.com' ${MAGENTO_AUTH_USERNAME} ${MAGENTO_AUTH_PASSWORD}
                      composer install -n --prefer-dist --no-progress
                      sudo chown circleci:circleci ~/.composer/
                      composer global config prefer-stable true
                      composer global config minimum-stability dev
                      composer global require algolia/magento2-tools

                      # We have to do this again because we restore the cache above, overwriting the vendor with the original.
                      cd ~/magento_directory/vendor/algolia
                      rm -rf algoliasearch-magento-2
                      cp -R ~/build_directory/algoliasearch-magento-2 ~/magento_directory/vendor/algolia
                      cd ~/magento_directory
                      composer dump-autoload
            - save_cache:
                  key: composer-v3-{{ checksum "composer.json" }}
                  paths:
                      - vendor
            - run:
                  name: Quality tools
                  command: |
                      sudo ~/.composer/vendor/bin/magento2-test ~/magento_directory/vendor/algolia/algoliasearch-magento-2 ~/.composer/vendor/bin/

workflows:
    version: 2
    build:
        jobs:
            - "magento-2.2"
            - "magento-2.3"
            - "quality-tools"
